-- MySQL Script generated by MySQL Workbench
-- fr. 04. des. 2015 kl. 10.05 +0100
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema s130533
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `s130533` ;

-- -----------------------------------------------------
-- Schema s130533
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `s130533` DEFAULT CHARACTER SET utf8 ;
USE `s130533` ;

-- -----------------------------------------------------
-- Table `s130533`.`tblChatUsers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s130533`.`tblChatUsers` ;

CREATE TABLE IF NOT EXISTS `s130533`.`tblChatUsers` (
  `chatUserID` INT NULL AUTO_INCREMENT,
  `username` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`chatUserID`))
ENGINE = InnoDB
COMMENT = 'chatagent application users';


-- -----------------------------------------------------
-- Table `s130533`.`tblChatQuestions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s130533`.`tblChatQuestions` ;

CREATE TABLE IF NOT EXISTS `s130533`.`tblChatQuestions` (
  `chatQuestionID` INT NULL AUTO_INCREMENT,
  `edx_questionID` INT NULL,
  `question_text` VARCHAR(250) NOT NULL,
  `asked_by_user` TINYINT(1) NULL,
  `fk_tblChatUsers` INT NOT NULL,
  PRIMARY KEY (`chatQuestionID`),
  INDEX `fk_tblChatQuestions_tblChatUsers1_idx` (`fk_tblChatUsers` ASC),
  CONSTRAINT `fk_tblChatQuestions_tblChatUsers1`
    FOREIGN KEY (`fk_tblChatUsers`)
    REFERENCES `s130533`.`tblChatUsers` (`chatUserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'presented and created questions';


-- -----------------------------------------------------
-- Table `s130533`.`tblStackExchange`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s130533`.`tblStackExchange` ;

CREATE TABLE IF NOT EXISTS `s130533`.`tblStackExchange` (
  `stackexchangeID` INT NULL AUTO_INCREMENT,
  `stackexchange_link` LONGTEXT NOT NULL,
  `lookup_date` DATETIME NOT NULL,
  PRIMARY KEY (`stackexchangeID`))
ENGINE = InnoDB
COMMENT = 'StackExchange related information\n';


-- -----------------------------------------------------
-- Table `s130533`.`tblChatAnswers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s130533`.`tblChatAnswers` ;

CREATE TABLE IF NOT EXISTS `s130533`.`tblChatAnswers` (
  `chatAnswersID` INT NULL AUTO_INCREMENT,
  `answer_text` LONGTEXT NOT NULL,
  `is_answer_read` TINYINT(1) NOT NULL,
  `correct_answer` TINYINT(1) NOT NULL,
  `fk_tblStackExchange` INT NOT NULL,
  `fk_tblChatQuestions` INT NOT NULL,
  PRIMARY KEY (`chatAnswersID`),
  INDEX `fk_tblChatAnswers_tblStackOverflow1_idx` (`fk_tblStackExchange` ASC),
  INDEX `fk_tblChatAnswers_tblChatQuestions1_idx` (`fk_tblChatQuestions` ASC),
  CONSTRAINT `fk_tblStackOverflow`
    FOREIGN KEY (`fk_tblStackExchange`)
    REFERENCES `s130533`.`tblStackExchange` (`stackexchangeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblChatQuestions`
    FOREIGN KEY (`fk_tblChatQuestions`)
    REFERENCES `s130533`.`tblChatQuestions` (`chatQuestionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'presented answers';


-- -----------------------------------------------------
-- Table `s130533`.`tblFeedbackQuestion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s130533`.`tblFeedbackQuestion` ;

CREATE TABLE IF NOT EXISTS `s130533`.`tblFeedbackQuestion` (
  `feedbackQuestionID` INT NULL AUTO_INCREMENT,
  `feedback_msg` LONGTEXT NOT NULL,
  PRIMARY KEY (`feedbackQuestionID`))
ENGINE = InnoDB
COMMENT = 'The type of feedback, with the question/message for the user';


-- -----------------------------------------------------
-- Table `s130533`.`tblUserFeedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s130533`.`tblUserFeedback` ;

CREATE TABLE IF NOT EXISTS `s130533`.`tblUserFeedback` (
  `feedbackID` INT NULL AUTO_INCREMENT,
  `feedback_text` LONGTEXT NOT NULL,
  `fk_tblFeedbackType` INT NOT NULL,
  `fk_tblChatUsers` INT NOT NULL,
  PRIMARY KEY (`feedbackID`),
  INDEX `fk_tblUserFeedback_tblFeedbackType1_idx` (`fk_tblFeedbackType` ASC),
  INDEX `fk_tblUserFeedback_tblChatUsers1_idx` (`fk_tblChatUsers` ASC),
  CONSTRAINT `fk_tblFeedbackType`
    FOREIGN KEY (`fk_tblFeedbackType`)
    REFERENCES `s130533`.`tblFeedbackQuestion` (`feedbackQuestionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblUserFeedback_tblChatUsers1`
    FOREIGN KEY (`fk_tblChatUsers`)
    REFERENCES `s130533`.`tblChatUsers` (`chatUserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Feedback from the users';


-- -----------------------------------------------------
-- Table `s130533`.`tblEdxQuestions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s130533`.`tblEdxQuestions` ;

CREATE TABLE IF NOT EXISTS `s130533`.`tblEdxQuestions` (
  `edx_questionID` INT NOT NULL,
  `question_text` LONGTEXT NOT NULL,
  `question_link` LONGTEXT NOT NULL,
  PRIMARY KEY (`edx_questionID`))
ENGINE = InnoDB
COMMENT = 'dummy table, not in use';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
